/**
* $().validate(json);
* *rules:自定义规则
* *messages:提示信息
*/
$(document).ready(function(){

    $(".infoTable").validate({
        rules:{
            username:{
                required:true,
                rangelength:[3,20]
            },
            psw:{
                required:true,
                minlength:6
            },
            enpsw:{
                required:true,
                minlength:6,
                equalTo:"#psw"
            },
            name:"required",
            gender:"required",
            age:{
                    required:true,
                digits:true,
                range:[1,100]
            },
            birth:{
                required:true,
                date:true
            },
            card:{
                required:true,
                creditcard:true
            },
            email:{
                required:true,
                email:true
            },
            xueli:"required"
        },
        messages:{
            username:{
                required:"用户名不能为空！",
                rangelength:"用户名为3-20位"
            },
            psw:{
                required:"密码不可为空！",
                minlength:"密码不少于6位"
            },
            enpsw:{
                required:"确认密码不可为空！",
                minlength:"密码不少于6位",
                equalTo:"两次密码输入不一致"
            },
            name:{
                required:"真实姓名不可为空！"
            },
            age:{
                required:"年龄不可为空！",
                digits:"年龄输入必须为数字！",
                range:"请输入1~100范围内的数字！"
            },
            birth:{
                required:"出生年月不可为空！",
                date:"出生年月输入格式如‘2015/9/25’"
            },
            card:{
                required:"信用卡号不可为空！",
                creditcard:"请输入正确的信用卡号！"
            },
            email:{
                required:"邮箱地址不可为空！",
                email:"请输入正确的邮箱地址！"
            },
            xueli:{
                required:"请选择学历！"
            }
        }
    });
});
